adds validators for URLs
markbates/validate pull request #10
Opened 2017-07-02 08:37 UTC by niranjan92

https://github.com/markbates/validate/issues/9

Adds url resource validators

2017-07-04 11:24 UTC, markbates requested changes

2017-07-04 11:24 UTC, markbates commented on validators/url_is_present_test.go
> +		fmt.Println(errors)
Can you remove this print statement?

2017-07-04 11:24 UTC, markbates commented on validators/url_is_present.go
> +// IsValid performs the validation based on the email regexp match.
Not sure this documentation is correct here?

2017-07-04 20:40 UTC, niranjan92 commented
@markbates updated the PR

2017-07-05 16:11 UTC, merged

2017-07-05 16:11 UTC, markbates commented
Awesome! Thanks!