Add email like validators who don`t want big scary regex
markbates/validate pull request #11
Opened 2017-07-17 15:42 UTC by MrEhbr

Add simple email validator. Why I done this you can see difference beetwen Benchmarks

2017-07-17 19:47 UTC, markbates requested changes

2017-07-17 19:47 UTC, markbates commented on validators/email_is_present.go
> +type EmailLike struct {
Can you please comment this so people know the difference between `EmailIsPresent` and `EmailLike`?

2017-07-17 19:58 UTC, MrEhbr commented on validators/email_is_present.go
> +type EmailLike struct {
Sorry forgot

2017-07-18 15:23 UTC, MrEhbr commented
Done

2017-07-18 15:34 UTC, markbates approved these changes

2017-07-18 15:34 UTC, merged